# Generated by Django 2.2.5 on 2020-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopping_cart',
                'managed': False,
            },
        ),
    ]
