import 'package:flutter/material.dart';

ThemeData base = ThemeData(
  brightness: Brightness.light,
  primaryColor: Color.fromARGB(255, 3, 169, 243),
  accentColor: Color.fromARGB(255, 194, 224, 237),
  buttonColor: Color.fromARGB(255, 3, 169, 243),
  appBarTheme: AppBarTheme(
    iconTheme: IconThemeData(
      color: Colors.white
    ),
    textTheme: TextTheme(
      title: TextStyle(color: Colors.white,fontSize: 20)
    ),
    color: Color.fromARGB(255, 3, 169, 243),
  )
//MaterialColor primarySwatch,
//Brightness primaryColorBrightness,
//Color primaryColorLight,
//Color primaryColorDark,
//Color accentColor,
//Brightness accentColorBrightness,
//Color canvasColor,
//Color scaffoldBackgroundColor,
//Color bottomAppBarColor,
//Color cardColor,
//Color dividerColor,
//Color focusColor,
//Color hoverColor,
//Color highlightColor,
//Color splashColor,
//InteractiveInkFeatureFactory splashFactory,
//Color selectedRowColor,
//Color unselectedWidgetColor,
//Color disabledColor,
//Color buttonColor,
//ButtonThemeData buttonTheme,
//Color secondaryHeaderColor,
//Color textSelectionColor,
//Color cursorColor,
//Color textSelectionHandleColor,
//Color backgroundColor,
//Color dialogBackgroundColor,
//Color indicatorColor,
//Color hintColor,
//Color errorColor,
//Color toggleableActiveColor,
//String fontFamily,
//TextTheme textTheme,
//TextTheme primaryTextTheme,
//TextTheme accentTextTheme,
//InputDecorationTheme inputDecorationTheme,
//IconThemeData iconTheme,
//IconThemeData primaryIconTheme,
//IconThemeData accentIconTheme,
//SliderThemeData sliderTheme,
//TabBarTheme tabBarTheme,
//CardTheme cardTheme,
//ChipThemeData chipTheme,
//TargetPlatform platform,
//MaterialTapTargetSize materialTapTargetSize,
//PageTransitionsTheme pageTransitionsTheme,
//AppBarTheme appBarTheme,
//BottomAppBarTheme bottomAppBarTheme,
//ColorScheme colorScheme,
//DialogTheme dialogTheme,
//FloatingActionButtonThemeData floatingActionButtonTheme,
//Typography typography,
//CupertinoThemeData cupertinoOverrideTheme,
//SnackBarThemeData snackBarTheme,
//BottomSheetThemeData bottomSheetTheme
);