@protocol = http
@hostname = 203.195.149.30

@port = 8010

@host = {{protocol}}://{{hostname}}:{{port}}

POST {{host}}/api/user/code HTTP/1.1
content-type: application/json

{
    phone: 18297913123  
}

###
POST {{host}}/api/user/login HTTP/1.1
content-type: application/json

{
    phone: 18297913123
}