"""
Django settings for Fresh_market_online project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_i&-x#otx5%s3$4r8%g)5!!%pb06(lxs6j320lttg#4vhg06d%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Fresh_market_online',
    'LoginAPI',
    'CodeAPI',
    'UserInfoAPI',
    'GoodsAPI',
    'AddressAPI',
    'CartAPI',
    'LogoffAPI',
    'OrderAPI',
    'AdsAPI',
    'AdminXZN'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Fresh_market_online.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Fresh_market_online.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xzn',
        'USER':'root',
        #'PASSWORD':'123456',
        'PASSWORD':'XZN_123456',
        'HOST':'127.0.0.1',
        'PORT':'',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

'''
以下为simpleui的相关参数
用来美化后台
'''
SIMPLEUI_DEFAULT_THEME = 'green.css'  # 默认主题
# SIMPLEUI_ICON = {  # logo
#     'Goodss': 'far fa-lemon',
# }
# 如果SIMPLEUI_CONFIG中存在menus字段，将会覆盖系统默认菜单。并且menus中输出的菜单不会受权限控制。
SIMPLEUI_CONFIG = {
    'menus': [
        {
            'app': 'AdminXZN',
            'name': '鲜着呢系统后台',
            'icon': 'fas fa-calculator',
            'models': [{
                'name': '商品管理',
                'icon': 'far fa-lemon',
                'url': '/admin/Fresh_market_online/goods/'
            }, {
                'name': '订单管理',
                'icon': 'fas fa-receipt',
                'url': '/admin/Fresh_market_online/order/'
            }, {
                'name': '仓库管理',
                'icon': 'fas fa-warehouse',
                'url': '/admin/Fresh_market_online/warehouse/'
            }, {
                'name': '骑手管理',
                'icon': 'fas fa-horse',
                'url': '/admin/Fresh_market_online/deliveryman/'
            }, {
                'name': '用户管理',
                'icon': 'fa fa-user',
                'url': '/admin/Fresh_market_online/user/'
            }, {
                'name': '广告管理',
                'icon': 'fas fa-ad',
                'url': '/admin/Fresh_market_online/ads/'
            }]
        },
        {
            'app': 'auth',
            'name': '权限管理',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': '管理员',
                'icon': 'fas fa-user-cog',
                'url': 'auth/user/'
            },
                {
                    'name': '权限分组',
                    'icon': 'fa fa-users-cog',
                    'url': 'auth/group/'
                }]
        },
    ]
}
# 侧边栏主页链接
# SIMPLEUI_HOME_PAGE = 'https://github.com/FredCof/Fresh-supermarket-Online'  # 首页
# SIMPLEUI_HOME_TITLE = '来GitHub上看看我们'
# SIMPLEUI_HOME_ICON = 'fab fa-github'

# logo地址
SIMPLEUI_LOGO = '/static/admin/logo.png'
# SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'
SIMPLEUI_HOME_INFO = False
