# Generated by Django 2.1.8 on 2020-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=32)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('head_image_id', models.CharField(blank=True, max_length=32, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
