# Generated by Django 2.2.5 on 2020-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=20, null=True)),
                ('goods_type', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('warehouse_id', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.FloatField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('specification', models.CharField(max_length=255)),
                ('packaging', models.CharField(blank=True, max_length=255, null=True)),
                ('stockway', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField()),
                ('discount', models.FloatField()),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.CharField(blank=True, max_length=255, null=True)),
                ('promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_type', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
    ]
