# Generated by Django 2.2.5 on 2020-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('customer_id', models.IntegerField()),
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('consignee', models.CharField(max_length=255)),
                ('consignee_phone', models.CharField(max_length=255)),
                ('consignee_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('house_no', models.CharField(max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
    ]
