# Generated by Django 2.2.5 on 2020-05-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfoAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
